# Generated by Django 4.2.16 on 2024-12-04 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clusters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DAG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dag_id", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                ("is_paused", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("file_location", models.CharField(max_length=500)),
                ("last_parsed", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dags",
                        to="clusters.cluster",
                    ),
                ),
            ],
            options={
                "ordering": ["dag_id"],
                "unique_together": {("cluster", "dag_id")},
            },
        ),
        migrations.CreateModel(
            name="DAGRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=250)),
                ("state", models.CharField(max_length=50)),
                ("execution_date", models.DateTimeField()),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                ("external_trigger", models.BooleanField(default=False)),
                (
                    "dag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="dags.dag",
                    ),
                ),
            ],
            options={
                "ordering": ["-execution_date"],
                "unique_together": {("dag", "run_id")},
            },
        ),
        migrations.CreateModel(
            name="TaskInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=250)),
                ("state", models.CharField(max_length=50)),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                ("duration", models.FloatField(null=True)),
                ("try_number", models.IntegerField(default=1)),
                (
                    "dag_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_instances",
                        to="dags.dagrun",
                    ),
                ),
            ],
            options={
                "ordering": ["task_id", "-try_number"],
                "unique_together": {("dag_run", "task_id", "try_number")},
            },
        ),
    ]
