# Generated by Django 4.2.16 on 2024-12-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dag",
            name="schedule_interval",
            field=models.CharField(
                blank=True,
                help_text="Cron expression or interval (e.g. '@daily', '@hourly', '*/10 * * * *', '30m')",
                max_length=100,
                null=True,
            ),
        ),
    ]
