# Generated by Django 4.2.16 on 2024-12-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clusters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cluster",
            name="api_key",
        ),
        migrations.AddField(
            model_name="cluster",
            name="password",
            field=models.CharField(
                default="admin",
                help_text="Password for Airflow basic auth",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="username",
            field=models.CharField(
                default="admin",
                help_text="Username for Airflow basic auth",
                max_length=100,
            ),
        ),
    ]
