# Generated by Django 4.2.16 on 2024-12-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clusters", "0002_remove_cluster_api_key_cluster_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="cluster",
            name="cores_used",
            field=models.FloatField(default=0, help_text="Percentage of cores used"),
        ),
        migrations.AddField(
            model_name="cluster",
            name="memory_used",
            field=models.FloatField(default=0, help_text="Percentage of memory used"),
        ),
        migrations.AddField(
            model_name="cluster",
            name="pods_used",
            field=models.FloatField(default=0, help_text="Percentage of pods used"),
        ),
        migrations.AddField(
            model_name="cluster",
            name="release_name",
            field=models.CharField(
                blank=True,
                help_text="Release or deployment name",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="scheduler_healthy",
            field=models.BooleanField(
                default=False, help_text="Scheduler current health status"
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="total_cores",
            field=models.FloatField(default=0, help_text="Total number of CPU cores"),
        ),
        migrations.AddField(
            model_name="cluster",
            name="total_memory",
            field=models.FloatField(default=0, help_text="Total memory in GB"),
        ),
        migrations.AddField(
            model_name="cluster",
            name="total_pods",
            field=models.IntegerField(default=0, help_text="Total number of pods"),
        ),
        migrations.AddField(
            model_name="cluster",
            name="version",
            field=models.CharField(
                default="1.0", help_text="Cluster version", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="tags",
            field=models.ManyToManyField(blank=True, to="clusters.clustertag"),
        ),
    ]
